FROM node:20

USER node

WORKDIR /home/node

COPY --chown=node:node ../backend/package.json ./backend/

WORKDIR /home/node/backend

# RUN npm install -g dotenv-cli

RUN npm install

COPY --chown=node:node ../backend/ .

CMD ["npm", "run", "dev"]