FROM node:20

USER node

WORKDIR /home/node

COPY --chown=node:node ../frontend/package.json ./frontend/

WORKDIR /home/node/frontend

# RUN npm install -g dotenv-cli

RUN npm install

COPY --chown=node:node ../frontend/ .

RUN mkdir -p /home/node/frontend/.next && chown -R node:node /home/node/frontend/.next

CMD ["npm", "run", "dev"]